### ISSUE TITLE
Some minor doc nits

### ISSUE THREAD

**Issue by candlerb** [timeplus-io/docs#216]
Moved from https://github.com/timeplus-io/proton/discussions/833

-----

At https://docs.timeplus.com/glossary under "view"

> By default, views don't take any extra computing or storage resources. They are expected to the SQL definition when they are queried

Should this be "expanded" not "expected"?

-----

At https://www.timeplus.com/post/introducing-mutable-streams there is a formatting issue:

> You can also run a streaming query with historical data backfill  (e.g. select .. from my_stream where _tp_ time>now()-14d )

I think that should be `_tp_time` (probably needs Markdown quoting in single backticks)

-----

At https://docs.timeplus.com/eventtime

> When it's configured, we may set `trip_end` as the (default) event time
> ...
> This query uses `trip_start`, the default event time, to run the aggregation.

That's inconsistent: in the first sentence it said that `trip_end` was the default end time, and that agrees with the following clause:

>  If the passenger ends the trip on 00:01 at midnight, it will be included in the 00:00-00:59 time window.

But then it's also inconsistent with the following section:

> In some cases, you as the analyst, may want to focus on how many passengers get in the taxi, instead of leaving the taxi, in each hour, then you can set `trip_end` as the event time for the query via `tumble(taxi_data,trip_end,1h)`

I think those should say `trip_start`.

-----

At https://docs.timeplus.com/proton-ingest-api#push-data-to-timeplus

> The above method should work very well for most system integration. However, the column names will be repeatedly mentioned in the requested body.
> 
> We also provide a more performant solution to only list the column names once.
> 
> The request body is this format:

But then it goes on to show exactly the same format, i.e. the original example was already in the form that doesn't repeat the column names (so we don't know what that was)

-----

The list of functions appears to be incomplete. I notice for example that `unhex()` is mentioned in passing under [ipv6_num_to_string](https://docs.timeplus.com/functions_for_url#ipv6_num_to_string), but it doesn't seem to be documented elsewhere (although [hex](https://docs.timeplus.com/functions_for_text#hex) is)

**Comment by jovezhong** [comment]
Hi @candlerb , thanks for the ticket.

How about this? I will create a PR to address/discuss those items and will add you as the reviewer. This will be done in the next few hours

**Comment by jovezhong** [comment]
I just created the PR, please review (also invite you as collaborator for the project)
