### ISSUE TITLE
missing docs in mutable stream

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/docs#229]
https://github.com/user-attachments/assets/cb95017b-1557-457b-8632-fd170851e000

previous refactor related? this is first returned keyword. sql-commands but not found

**Comment by jovezhong** [comment]
Thanks. I updated the doc index on algolia/docsearch-scraper

The local script I ran is

> docker run -it --env-file=docSearch.env -e "CONFIG=$(cat ~/Dev/algolia_publicdocs.json | jq -r tostring)" algolia/docsearch-scraper
